version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - scd-network

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/task-management
      - JWT_SECRET=TaskManagementSecretKey2025
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=Admin123!
    depends_on:
      - mongodb
    networks:
      - scd-network

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - scd-network

networks:
  scd-network:
    driver: bridge

volumes:
  mongodb_data:
