name: Build and Deploy to Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./app/backend
          push: true
          tags: hariskhan062/mernnotesapp-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./app/frontend
          push: true
          tags: hariskhan062/mernnotesapp-frontend:latest

      - name: Deploy to Minikube
        shell: cmd
        run: |
          kubectl create namespace scd-project --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f kubernetes/ -n scd-project
          kubectl rollout status deployment/backend -n scd-project
          kubectl rollout status deployment/frontend -n scd-project
